version: 1
disable_existing_loggers: false


formatters:
    standard:
        format: "TEST - %(asctime)s - %(process)d - %(name)s - %(levelname)5s - %(filename)12s - %(lineno)4d - %(message)s"
    error:
        format: "TEST - %(asctime)s.%(process)d.%(processName)s - %(levelname)s - %(name)s.%(funcName)s() - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: cloghandler.ConcurrentRotatingFileHandler
        level: INFO
        formatter: standard
        filename: logs/app.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    error_file_handler:
        class: cloghandler.ConcurrentRotatingFileHandler
        level: ERROR
        formatter: error
        filename: logs/app.error.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    debug_file_handler:
        class: cloghandler.ConcurrentRotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: logs/app.debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    critical_file_handler:
        class: cloghandler.ConcurrentRotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: logs/app.critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

    warn_file_handler:
        class: cloghandler.ConcurrentRotatingFileHandler
        level: WARN
        formatter: standard
        filename: logs/app.warn.log
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

root:
    level: DEBUG
    handlers: []
    propagate: yes

loggers:
    test:
        level: DEBUG
        handlers: [debug_file_handler, console]
        propagate: no